name: Deploy react library - react-sticky-puzzle
on:
  push:
    branches: [main]
jobs:
  deploy-library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          registry-url: "https://registry.npmjs.org"
      - name: Deploying react component
        run: |
          yarn
          yarn install
          yarn run build:component
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy-demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          yarn install
          git config --global user.email jhonyvegacuya24@gmail.com 
          git config --global user.name jhony-24
          yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}