name: Deploy react library - react-sticky-puzzle
on:
  push:
    branches: [main]
jobs:
  deploy-library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          registry-url: "https://registry.npmjs.org"
      - name: Deploying react component
        run: |
          yarn
          yarn install
          yarn run build:component
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
